plugins {
    id 'multiloader-loader'
    id 'net.neoforged.moddev.legacyforge'
}

legacyForge {
    version = "${minecraft_version}-${forge_version}"
    // Automatically enable Forge AccessTransformers if the file exists
    def at = project(':common').file('src/main/resources/META-INF/accesstransformer.cfg')
    if (at.exists()) {
        accessTransformers.from(at.absolutePath)
    }
    runs {
        configureEach {
            systemProperty('forge.enabledGameTestNamespaces', mod_id)
            ideName = "Forge ${it.name.capitalize()} (${project.path})" // Unify the run config names with fabric
        }
        client {
            client()
            gameDirectory = this.mkdir(this.file('runs/client'))
            jvmArgument('-Dbonehitboxlib.debugContacts=true')
            jvmArgument('-Dbonehitboxlib.manualTestFeedback=true')
            if (project.hasProperty('quickplay_world')) {
                programArguments.addAll '--quickPlaySingleplayer', project.property('quickplay_world').toString()
            }
        }
        data {
            data()
            gameDirectory = this.mkdir(this.file('runs/data'))
            // DataGen can be run by - "./gradlew :forge:runData" in Terminal.
            // Specify the modid for data generation, where to output the resulting resource, and where to look for existing resources.
            programArguments.addAll '--mod', project.mod_id, '--all', '--output', file('src/generated/resources/').getAbsolutePath(), '--existing', file('src/main/resources/').getAbsolutePath()
        }
        server {
            server()
            this.file('runs/server').createParentDirectories()
            gameDirectory = this.mkdir(this.file('runs/server'))
        }
    }
    mods {
        "${mod_id}" {
            sourceSet sourceSets.main
        }
    }
}

sourceSets.main.resources { srcDir 'src/generated/resources' }

dependencies {
    annotationProcessor("net.fabricmc:sponge-mixin:0.17.3+mixin.0.8.7")
    annotationProcessor("io.github.llamalad7:mixinextras-common:0.5.0")
    compileOnly("io.github.llamalad7:mixinextras-common:0.5.0")
    jarJar(implementation("io.github.llamalad7:mixinextras-forge:0.5.0")) {
        version { strictly '[0.5.0,0.6.0)'; prefer '0.5.0' }
    }
    modCompileOnly("software.bernie.geckolib:geckolib-forge-${minecraft_version}:${geckolib_version}")
    if (!project.hasProperty('without_geckolib')) {
        modRuntimeOnly("software.bernie.geckolib:geckolib-forge-${minecraft_version}:${geckolib_version}")
    }
}

// Implement mcgradleconventions loader attribute
def loaderAttribute = Attribute.of('io.github.mcgradleconventions.loader', String)
['apiElements', 'runtimeElements', 'sourcesElements', 'javadocElements'].each { variant ->
    configurations.named(variant) {
        attributes {
            attribute(loaderAttribute, 'forge')
        }
    }
}
sourceSets.configureEach {
    [it.compileClasspathConfigurationName, it.runtimeClasspathConfigurationName].each { variant ->
        configurations.named(variant) {
            attributes {
                attribute(loaderAttribute, 'forge')
            }
        }
    }
}

mixin {
    add(sourceSets.main, "${mod_id}.refmap.json")
    config("${mod_id}.mixins.json")
}
jar {
    finalizedBy("reobfJar")
    manifest.attributes("MixinConfigs": "${mod_id}.mixins.json")
}
