plugins {
    id 'java-library'
    id 'maven-publish'
}

repositories {
    mavenLocal()
    mavenCentral()
    exclusiveContent {
        forRepository {
            maven {
                name = 'GeckoLib'
                url = uri('https://dl.cloudsmith.io/public/geckolib3/geckolib/maven/')
            }
        }
        filter {
            includeGroupAndSubgroups('com.geckolib')
        }
    }
    exclusiveContent {
        forRepository {
            maven {
                name = 'Fuzs Mod Resources'
                url = uri('https://raw.githubusercontent.com/Fuzss/modresources/main/maven/')
            }
        }
        filter {
            includeGroupAndSubgroups('fuzs.forgeconfigapiport')
        }
    }
    maven {
        name = 'Fabric'
        url = uri('https://maven.fabricmc.net')
        content {
            includeGroupAndSubgroups('net.fabricmc')
        }
    }
    maven {
        name = 'NeoForge'
        url = uri('https://maven.neoforged.net/releases')
        content {
            includeGroupAndSubgroups('net.neoforged')
        }
    }
}

base {
    archivesName = "${mod_id}-${project.name}-${minecraft_version}"
}

java {
    toolchain.languageVersion = JavaLanguageVersion.of(java_version)
    withSourcesJar()
    withJavadocJar()
}

tasks.withType(Javadoc).configureEach {
    options.encoding = 'UTF-8'
    options.charSet = 'UTF-8'
    options.docEncoding = 'UTF-8'
}

tasks.withType(Jar).configureEach {
    includeEmptyDirs = false
    from(rootProject.file('LICENSE')) {
        rename { "${it}_${mod_name}" }
    }
}

jar {

    manifest {
        attributes([
                'Specification-Title'   : mod_name,
                'Specification-Vendor'  : mod_author,
                'Specification-Version' : project.jar.archiveVersion,
                'Implementation-Title'  : project.name,
                'Implementation-Version': project.jar.archiveVersion,
                'Implementation-Vendor' : mod_author,
                'Built-On-Minecraft'    : minecraft_version
        ])
    }
}

processResources {
    var expandProps = [
            'version'                      : version,
            'group'                        : project.group, //Else we target the task's group.
            'minecraft_version'            : minecraft_version,
            'minecraft_version_range'      : minecraft_version_range,
            'fabric_version'               : fabric_version,
            'fabric_loader_version'        : fabric_loader_version,
            'fabric_rendering_v1_version'  : fabric_rendering_v1_version,
            'geckolib_version'             : geckolib_version,
            'forge_config_api_port_version': forge_config_api_port_version,
            'mod_name'                     : mod_name,
            'mod_author'                   : mod_author,
            'mod_id'                       : mod_id,
            'license'                      : license,
            'description'                  : project.description,
            'neoforge_version'             : neoforge_version,
            'neoforge_loader_version_range': neoforge_loader_version_range,
            'credits'                      : credits,
            'java_version'                 : java_version
    ]

    var jsonExpandProps = expandProps.collectEntries {
        key, value -> [(key): value instanceof String ? value.replace('\n', '\\\\n') : value]
    }

    filesMatching(['META-INF/mods.toml', 'META-INF/neoforge.mods.toml']) {
        expand expandProps
    }

    filesMatching(['pack.mcmeta', 'fabric.mod.json']) {
        expand jsonExpandProps
    }

    inputs.properties(expandProps)
}

publishing {
    publications {
        register('mavenJava', MavenPublication) {
            artifactId base.archivesName.get()
            from components.java
        }
    }
    repositories {
        maven {
            url System.getenv('local_maven_url')
        }
    }
}
